version: '3.1'
services:
  web:
    command: python3 main.py
    image: isratnipa/nipa:a2.4
    platform: linux/x86_64
    ports:
      - 3000:80
    expose:
      - 80 

    ports:
      - 8050:80

    environment:
      - HOST=0.0.0.0
      - PORT=80

    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st124984.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is web-st125171
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124984.rule=Host(`st124984.mlflow.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124984.tls=true
      - traefik.http.routers.web-st124984.tls.certresolver=production
      - traefik.http.routers.web-st124984.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true
